import Payment.Payments

fun main()
{
    println("введите стоимость заказа")
    var order= readLine()!!.toInt()
    println("введите карту")
    var map= readLine()!!.toInt()
    println("хотите заблокировать карту (да/нет)")
    var block= readLine()!!.toString()
    var client1=Client(order,"сбербанк",map,block,5000)
    client1.status()
    client1.info()
    client1.purchase()
    println("администратор введи количество действий с картой")
    var deistvia= readLine()!!.toDouble()
    println("введите карту")
     map= readLine()!!.toInt()
    var administrator1=Administrator("Василий Васильевичь Вардунков",deistvia,"сбербанк",map,"разблокированна",0)
    administrator1.chec()
    administrator1.sotrudnik()
    administrator1.rabota()
    println("введите карту")
    map= readLine()!!.toInt()
    println("введите статус карты(заблокированна/разблокированная)")
    var bloc=readLine()!!.toString()
    var banc=Payments("сбербанк",map,bloc,4000)
    banc.GetBloc()
    banc.bank()
    banc.maps()
}